-- ============================================================================
-- Tamil Business Tribe — FULL DATABASE MIGRATION
-- ============================================================================
-- Purpose: recreate every table, index, RLS policy, storage bucket, and the
-- minimal "functional default" seed data this codebase needs, inside a
-- DIFFERENT Supabase project (your existing/target project).
--
-- How to use:
--   1. Open your TARGET Supabase project -> SQL Editor -> New query.
--   2. Paste this entire file and click "Run".
--   3. It is idempotent (safe to re-run) — every CREATE uses IF NOT EXISTS
--      and every CREATE POLICY is preceded by a matching DROP POLICY IF EXISTS.
--   4. After running, update:
--        - admin-app/.env -> SUPABASE_URL / SUPABASE_KEY (service role key)
--          of the TARGET project, plus ANTHROPIC_API_KEY / CLAUDE_MODEL.
--        - lib/main.dart -> the hardcoded Supabase URL + anon key in main()
--          to the TARGET project's values.
--   5. Storage buckets are created at the bottom of this file (Section 15).
--      Supabase Storage bucket creation via SQL works, but it's worth opening
--      Dashboard -> Storage afterwards to visually confirm all 3 buckets
--      (community, ai-content, support-attachments) show up and are Public.
--
-- This file was generated by reverse-engineering every `supabase.from(...)`
-- / `.storage.from(...)` call across admin-app/ and lib/ against the existing
-- *_schema.sql files already in this repo, since a few tables (the E-book
-- module) were created by hand in Supabase Studio and were never scripted.
-- ============================================================================

-- Required for gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- ============================================================================
-- 1. POSTS  (Community feed items — admin-managed, with approval flow)
-- ============================================================================
CREATE TABLE IF NOT EXISTS posts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL,
  time VARCHAR(100) DEFAULT 'Just now',
  badge VARCHAR(100),
  badge_color VARCHAR(50) DEFAULT '#CC0000',
  avatar_url TEXT,
  content TEXT NOT NULL,
  has_video BOOLEAN DEFAULT FALSE,
  video_thumbnail TEXT,
  has_images BOOLEAN DEFAULT FALSE,
  images TEXT[] DEFAULT '{}',
  likes INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  is_liked BOOLEAN DEFAULT FALSE,
  is_bookmarked BOOLEAN DEFAULT FALSE,
  is_following BOOLEAN DEFAULT FALSE,
  is_mentor BOOLEAN DEFAULT FALSE,
  is_approved BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Safe to re-run: patches an already-created table that predates is_approved.
ALTER TABLE posts ADD COLUMN IF NOT EXISTS is_approved BOOLEAN NOT NULL DEFAULT TRUE;

CREATE INDEX IF NOT EXISTS idx_posts_is_approved ON posts(is_approved);
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts(created_at);

ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access" ON posts;
CREATE POLICY "Allow public read access" ON posts FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow all access for admin portal" ON posts;
CREATE POLICY "Allow all access for admin portal" ON posts FOR ALL USING (true) WITH CHECK (true);


-- ============================================================================
-- 2. HOME CAROUSEL
-- ============================================================================
CREATE TABLE IF NOT EXISTS home_carousel (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  subtitle TEXT,
  description TEXT,
  media_type VARCHAR(50) DEFAULT 'image', -- 'image' or 'video'
  media_url TEXT NOT NULL,
  thumbnail_url TEXT,
  button_text VARCHAR(100),
  button_link TEXT,
  sort_order INTEGER DEFAULT 0,
  status VARCHAR(50) DEFAULT 'active', -- 'active' or 'inactive'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE home_carousel ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access" ON home_carousel;
CREATE POLICY "Allow public read access" ON home_carousel FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow all access for admin portal" ON home_carousel;
CREATE POLICY "Allow all access for admin portal" ON home_carousel FOR ALL USING (true) WITH CHECK (true);


-- ============================================================================
-- 3. PODCAST  (Categories, Series, Episodes, Listening Progress)
-- ============================================================================
CREATE TABLE IF NOT EXISTS podcast_categories (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  status VARCHAR(50) DEFAULT 'active',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS podcast_series (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  description TEXT,
  cover_image TEXT,
  status VARCHAR(50) DEFAULT 'active',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS podcast_episodes (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  description TEXT,
  category_id UUID REFERENCES podcast_categories(id) ON DELETE SET NULL,
  series_id UUID REFERENCES podcast_series(id) ON DELETE SET NULL,
  cover_image TEXT,
  audio_url TEXT NOT NULL,
  duration_seconds INTEGER DEFAULT 0,
  speaker VARCHAR(255),
  tags TEXT[] DEFAULT '{}',
  is_featured BOOLEAN DEFAULT false,
  status VARCHAR(50) DEFAULT 'active',
  publish_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS podcast_progress (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id TEXT NOT NULL,
  episode_id UUID REFERENCES podcast_episodes(id) ON DELETE CASCADE,
  current_position_seconds INTEGER DEFAULT 0,
  total_duration_seconds INTEGER DEFAULT 0,
  completed BOOLEAN DEFAULT false,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, episode_id)
);

CREATE INDEX IF NOT EXISTS idx_podcast_episodes_category ON podcast_episodes(category_id);
CREATE INDEX IF NOT EXISTS idx_podcast_episodes_series ON podcast_episodes(series_id);
CREATE INDEX IF NOT EXISTS idx_podcast_episodes_status ON podcast_episodes(status);
CREATE INDEX IF NOT EXISTS idx_podcast_progress_user ON podcast_progress(user_id);

ALTER TABLE podcast_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE podcast_series ENABLE ROW LEVEL SECURITY;
ALTER TABLE podcast_episodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE podcast_progress ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access" ON podcast_categories;
DROP POLICY IF EXISTS "Allow public read access" ON podcast_series;
DROP POLICY IF EXISTS "Allow public read access" ON podcast_episodes;
DROP POLICY IF EXISTS "Allow public read access" ON podcast_progress;
CREATE POLICY "Allow public read access" ON podcast_categories FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON podcast_series FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON podcast_episodes FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON podcast_progress FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow all access for admin portal" ON podcast_categories;
DROP POLICY IF EXISTS "Allow all access for admin portal" ON podcast_series;
DROP POLICY IF EXISTS "Allow all access for admin portal" ON podcast_episodes;
DROP POLICY IF EXISTS "Allow all access for admin portal" ON podcast_progress;
CREATE POLICY "Allow all access for admin portal" ON podcast_categories FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for admin portal" ON podcast_series FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for admin portal" ON podcast_episodes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for admin portal" ON podcast_progress FOR ALL USING (true) WITH CHECK (true);

-- Functional default: the app expects at least a few categories to exist.
INSERT INTO podcast_categories (name, slug, status, sort_order) VALUES
  ('Mindset', 'mindset', 'active', 1),
  ('Business', 'business', 'active', 2),
  ('Growth', 'growth', 'active', 3),
  ('Leadership', 'leadership', 'active', 4)
ON CONFLICT (slug) DO NOTHING;


-- ============================================================================
-- 4. E-BOOKS  (Categories, Books, Banners, Bookmarks, Reading Progress)
-- ----------------------------------------------------------------------------
-- NOTE: these 5 tables did NOT exist as scripted SQL anywhere in the original
-- repo (only RLS-policy statements in ebook_schema.sql, assuming the tables
-- already existed from being created by hand in Supabase Studio). This
-- CREATE TABLE block was reconstructed from every column referenced in
-- admin-app/server.js (`EBOOK_SELECT`, insert/update bodies) and
-- lib/ebook_service.dart (`_normalizeBook`, `_normalizeBanner`).
-- ============================================================================
CREATE TABLE IF NOT EXISTS ebook_categories (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  status VARCHAR(50) DEFAULT 'active',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ebooks (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  description TEXT,
  author VARCHAR(255),
  category_id UUID REFERENCES ebook_categories(id) ON DELETE SET NULL,
  cover_image TEXT,
  pdf_url TEXT,
  content_url TEXT,
  total_pages INTEGER DEFAULT 0,
  reading_time VARCHAR(50),
  is_featured BOOLEAN DEFAULT false,
  sort_order INTEGER DEFAULT 0,
  publish_date DATE DEFAULT CURRENT_DATE,
  status VARCHAR(50) DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ebook_banners (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  subtitle TEXT,
  background_image TEXT,
  button_text VARCHAR(100),
  button_link TEXT,
  status VARCHAR(50) DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ebook_bookmarks (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id TEXT NOT NULL,
  book_id UUID REFERENCES ebooks(id) ON DELETE CASCADE,
  page_number INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, book_id)
);

CREATE TABLE IF NOT EXISTS ebook_progress (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id TEXT NOT NULL,
  book_id UUID REFERENCES ebooks(id) ON DELETE CASCADE,
  current_page INTEGER DEFAULT 0,
  total_pages INTEGER DEFAULT 0,
  progress_percentage NUMERIC(5,2) DEFAULT 0,
  completed BOOLEAN DEFAULT false,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, book_id)
);

CREATE INDEX IF NOT EXISTS idx_ebooks_category ON ebooks(category_id);
CREATE INDEX IF NOT EXISTS idx_ebooks_status ON ebooks(status);
CREATE INDEX IF NOT EXISTS idx_ebook_bookmarks_user ON ebook_bookmarks(user_id);
CREATE INDEX IF NOT EXISTS idx_ebook_progress_user ON ebook_progress(user_id);

ALTER TABLE ebook_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE ebooks ENABLE ROW LEVEL SECURITY;
ALTER TABLE ebook_banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE ebook_bookmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE ebook_progress ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access" ON ebook_categories;
DROP POLICY IF EXISTS "Allow public read access" ON ebooks;
DROP POLICY IF EXISTS "Allow public read access" ON ebook_progress;
DROP POLICY IF EXISTS "Allow public read access" ON ebook_bookmarks;
DROP POLICY IF EXISTS "Allow public read access" ON ebook_banners;
CREATE POLICY "Allow public read access" ON ebook_categories FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON ebooks FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON ebook_progress FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON ebook_bookmarks FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON ebook_banners FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow all access for admin portal" ON ebook_categories;
DROP POLICY IF EXISTS "Allow all access for admin portal" ON ebooks;
DROP POLICY IF EXISTS "Allow all access for admin portal" ON ebook_progress;
DROP POLICY IF EXISTS "Allow all access for admin portal" ON ebook_bookmarks;
DROP POLICY IF EXISTS "Allow all access for admin portal" ON ebook_banners;
CREATE POLICY "Allow all access for admin portal" ON ebook_categories FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for admin portal" ON ebooks FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for admin portal" ON ebook_progress FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for admin portal" ON ebook_bookmarks FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for admin portal" ON ebook_banners FOR ALL USING (true) WITH CHECK (true);


-- ============================================================================
-- 5. MORNING RITUAL — Habits & Buttons Config
-- ============================================================================
CREATE TABLE IF NOT EXISTS habits (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  icon VARCHAR(100) DEFAULT 'fa-sun',
  raw_question TEXT NOT NULL,
  highlight_word VARCHAR(255) DEFAULT '',
  subtitle VARCHAR(255) DEFAULT '',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS buttons_config (
  id VARCHAR(50) PRIMARY KEY DEFAULT 'default',
  yes_label VARCHAR(100) DEFAULT 'Yes',
  not_yet_label VARCHAR(100) DEFAULT 'Not Yet',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE habits ENABLE ROW LEVEL SECURITY;
ALTER TABLE buttons_config ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access for habits" ON habits;
CREATE POLICY "Allow public read access for habits" ON habits FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow all access for admin on habits" ON habits;
CREATE POLICY "Allow all access for admin on habits" ON habits FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access for buttons_config" ON buttons_config;
CREATE POLICY "Allow public read access for buttons_config" ON buttons_config FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow all access for admin on buttons_config" ON buttons_config;
CREATE POLICY "Allow all access for admin on buttons_config" ON buttons_config FOR ALL USING (true) WITH CHECK (true);

-- Functional default: at least one habit + the single buttons_config row.
INSERT INTO habits (icon, raw_question, highlight_word, subtitle, sort_order)
SELECT 'fa-sun', 'Did you finish this new habit?', 'new habit', 'Start your day right.', 0
WHERE NOT EXISTS (SELECT 1 FROM habits);

INSERT INTO buttons_config (id, yes_label, not_yet_label)
VALUES ('default', 'Yes', 'Not Yet')
ON CONFLICT (id) DO NOTHING;


-- ============================================================================
-- 6. LEGAL PAGES  (Terms & Conditions, Privacy Policy)
-- ============================================================================
CREATE TABLE IF NOT EXISTS legal_pages (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  type VARCHAR(20) NOT NULL UNIQUE CHECK (type IN ('terms', 'privacy')),
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  status VARCHAR(50) DEFAULT 'active',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_legal_pages_type ON legal_pages(type);

ALTER TABLE legal_pages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access" ON legal_pages;
CREATE POLICY "Allow public read access" ON legal_pages FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow all access for admin portal" ON legal_pages;
CREATE POLICY "Allow all access for admin portal" ON legal_pages FOR ALL USING (true) WITH CHECK (true);

-- Functional default: mobile app expects a 'terms' and 'privacy' row to exist.
-- EDIT the content below (or overwrite it from the admin panel afterwards).
INSERT INTO legal_pages (type, title, content, status, sort_order) VALUES
  ('terms', 'Terms & Conditions', 'Add your Terms & Conditions content here.', 'active', 1),
  ('privacy', 'Privacy Policy', 'Add your Privacy Policy content here.', 'active', 2)
ON CONFLICT (type) DO NOTHING;


-- ============================================================================
-- 7. MOBILE NOTIFICATIONS  (admin -> mobile broadcast)
-- ============================================================================
CREATE TABLE IF NOT EXISTS mobile_notifications (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  type VARCHAR(50) NOT NULL DEFAULT 'community_post',
  reference_id UUID,
  reference_type VARCHAR(50),
  is_read BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE mobile_notifications ADD COLUMN IF NOT EXISTS is_read BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS idx_mobile_notifications_created_at ON mobile_notifications(created_at);
CREATE INDEX IF NOT EXISTS idx_mobile_notifications_is_read ON mobile_notifications(is_read);

ALTER TABLE mobile_notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access" ON mobile_notifications;
CREATE POLICY "Allow public read access" ON mobile_notifications FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow admin portal full access" ON mobile_notifications;
CREATE POLICY "Allow admin portal full access" ON mobile_notifications FOR ALL USING (true) WITH CHECK (true);


-- ============================================================================
-- 8. ADMIN NOTIFICATIONS  (mobile -> admin, e.g. new tickets/feedback)
-- ============================================================================
CREATE TABLE IF NOT EXISTS admin_notifications (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  type VARCHAR(50) NOT NULL,
  reference_id UUID,
  reference_type VARCHAR(50),
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_admin_notifications_is_read ON admin_notifications(is_read);
CREATE INDEX IF NOT EXISTS idx_admin_notifications_created_at ON admin_notifications(created_at);

ALTER TABLE admin_notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert" ON admin_notifications;
CREATE POLICY "Allow public insert" ON admin_notifications FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow admin portal full access" ON admin_notifications;
CREATE POLICY "Allow admin portal full access" ON admin_notifications FOR ALL USING (true) WITH CHECK (true);


-- ============================================================================
-- 9. SUPPORT MODULE  (Settings, Categories, FAQs, Tickets, Feedback)
-- ============================================================================
CREATE TABLE IF NOT EXISTS support_settings (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title VARCHAR(255) NOT NULL DEFAULT 'Support Center',
  subtitle TEXT,
  whatsapp_number VARCHAR(50),
  phone_number VARCHAR(50),
  email VARCHAR(255),
  website_url TEXT,
  support_timing VARCHAR(255),
  address TEXT,
  button_text VARCHAR(100) DEFAULT 'Contact Us',
  banner_image TEXT,
  status VARCHAR(50) DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS support_categories (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  description TEXT,
  icon TEXT,
  status VARCHAR(50) DEFAULT 'active',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS support_faqs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  question VARCHAR(500) NOT NULL,
  answer TEXT NOT NULL,
  category_id UUID REFERENCES support_categories(id) ON DELETE SET NULL,
  status VARCHAR(50) DEFAULT 'active',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS support_tickets (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(50),
  subject VARCHAR(255) NOT NULL,
  category_id UUID REFERENCES support_categories(id) ON DELETE SET NULL,
  message TEXT NOT NULL,
  attachment_url TEXT,
  status VARCHAR(50) NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'in-progress', 'resolved', 'closed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS support_feedback (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255),
  rating INTEGER CHECK (rating IS NULL OR (rating BETWEEN 1 AND 5)),
  message TEXT NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'in-progress', 'resolved', 'closed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_support_faqs_category ON support_faqs(category_id);
CREATE INDEX IF NOT EXISTS idx_support_faqs_status ON support_faqs(status);
CREATE INDEX IF NOT EXISTS idx_support_tickets_status ON support_tickets(status);
CREATE INDEX IF NOT EXISTS idx_support_tickets_category ON support_tickets(category_id);
CREATE INDEX IF NOT EXISTS idx_support_feedback_status ON support_feedback(status);

ALTER TABLE support_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_faqs ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_feedback ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access" ON support_settings;
DROP POLICY IF EXISTS "Allow public read access" ON support_categories;
DROP POLICY IF EXISTS "Allow public read access" ON support_faqs;
CREATE POLICY "Allow public read access" ON support_settings FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON support_categories FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON support_faqs FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow all access for admin portal" ON support_settings;
DROP POLICY IF EXISTS "Allow all access for admin portal" ON support_categories;
DROP POLICY IF EXISTS "Allow all access for admin portal" ON support_faqs;
CREATE POLICY "Allow all access for admin portal" ON support_settings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for admin portal" ON support_categories FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for admin portal" ON support_faqs FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public insert" ON support_tickets;
CREATE POLICY "Allow public insert" ON support_tickets FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow admin portal full access" ON support_tickets;
CREATE POLICY "Allow admin portal full access" ON support_tickets FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public insert" ON support_feedback;
CREATE POLICY "Allow public insert" ON support_feedback FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow admin portal full access" ON support_feedback;
CREATE POLICY "Allow admin portal full access" ON support_feedback FOR ALL USING (true) WITH CHECK (true);

-- Functional default: single support_settings row + starter categories.
-- EDIT the contact details below to your own.
INSERT INTO support_settings (title, subtitle, whatsapp_number, phone_number, email, website_url, support_timing, address, button_text, status)
SELECT
  'Support Center', 'How can we help you today?',
  '', '', '', '', 'Mon - Sat, 9:00 AM - 7:00 PM', '', 'Contact Us', 'active'
WHERE NOT EXISTS (SELECT 1 FROM support_settings);

INSERT INTO support_categories (name, slug, description, status, sort_order) VALUES
  ('Payments', 'payments', 'Subscription, billing, invoices, and refunds', 'active', 1),
  ('Technicals', 'technicals', 'Course access, login issues, and app performance', 'active', 2),
  ('Community', 'community', 'Account privacy, community rules, and reporting abuse', 'active', 3)
ON CONFLICT (slug) DO NOTHING;


-- ============================================================================
-- 10. TBT POINTS  (Activity Log, Level Definitions)
-- ============================================================================
CREATE TABLE IF NOT EXISTS tbt_activity_log (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id TEXT NOT NULL,
  points INTEGER NOT NULL DEFAULT 0,
  source VARCHAR(50) NOT NULL DEFAULT 'task_completion',
  activity_date DATE NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')::DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tbt_levels (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  level_number INTEGER NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  required_points INTEGER NOT NULL,
  reward VARCHAR(255),
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tbt_activity_log_user ON tbt_activity_log(user_id);
CREATE INDEX IF NOT EXISTS idx_tbt_activity_log_user_date ON tbt_activity_log(user_id, activity_date);

ALTER TABLE tbt_activity_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbt_levels ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access" ON tbt_activity_log;
DROP POLICY IF EXISTS "Allow public read access" ON tbt_levels;
CREATE POLICY "Allow public read access" ON tbt_activity_log FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON tbt_levels FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow all access for admin portal" ON tbt_activity_log;
DROP POLICY IF EXISTS "Allow all access for admin portal" ON tbt_levels;
CREATE POLICY "Allow all access for admin portal" ON tbt_activity_log FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for admin portal" ON tbt_levels FOR ALL USING (true) WITH CHECK (true);

INSERT INTO tbt_levels (level_number, name, description, required_points, reward, sort_order) VALUES
  (1, 'Starter', 'Complete your first tasks and get the ball rolling.', 200, 'Bronze Badge', 1),
  (2, 'Builder', 'Keep the momentum going with consistent daily progress.', 300, 'Silver Badge', 2),
  (3, 'Achiever', 'Turn consistency into real, visible business results.', 500, 'Gold Badge', 3),
  (4, 'Momentum Maker', 'Push through the mid-program grind and compound your gains.', 800, 'Platinum Badge', 4),
  (5, 'Elite Performer', 'Join the top tier of consistently high-performing members.', 1200, 'Elite Badge', 5),
  (6, 'Legend', 'Complete the full journey and cement your status as a TBT Legend.', 2000, 'Legend Trophy', 6)
ON CONFLICT (level_number) DO NOTHING;


-- ============================================================================
-- 11. TBT TASKS  (90-Day Task path)
-- ============================================================================
CREATE TABLE IF NOT EXISTS tbt_tasks (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  task_order INTEGER NOT NULL UNIQUE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  required_action VARCHAR(255),
  reward_points INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(50) DEFAULT 'active',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tbt_task_completions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id TEXT NOT NULL,
  task_id UUID REFERENCES tbt_tasks(id) ON DELETE CASCADE,
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, task_id)
);

CREATE INDEX IF NOT EXISTS idx_tbt_tasks_order ON tbt_tasks(task_order);
CREATE INDEX IF NOT EXISTS idx_tbt_task_completions_user ON tbt_task_completions(user_id);

ALTER TABLE tbt_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbt_task_completions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access" ON tbt_tasks;
DROP POLICY IF EXISTS "Allow public read access" ON tbt_task_completions;
CREATE POLICY "Allow public read access" ON tbt_tasks FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON tbt_task_completions FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow all access for admin portal" ON tbt_tasks;
DROP POLICY IF EXISTS "Allow all access for admin portal" ON tbt_task_completions;
CREATE POLICY "Allow all access for admin portal" ON tbt_tasks FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for admin portal" ON tbt_task_completions FOR ALL USING (true) WITH CHECK (true);

INSERT INTO tbt_tasks (task_order, title, description, required_action, reward_points, status, sort_order) VALUES
  (1, 'Attend Onboarding Call',
     'Attend the live onboarding kick-off session or watch the video replay to align on the core 90-day execution framework.',
     'Complete your onboarding profile and join the community groups.', 250, 'active', 1),
  (2, 'Define Your Customer Segment',
     'Define the high-value target audience for your product. Focus on psychological triggers, spending capacity, and pain points that align with your unique value proposition.',
     'Fill in the Customer Segment section of your Business Model Canvas.', 500, 'active', 2),
  (3, 'Conduct 5 Customer Interviews',
     'Validate the core problem statement with potential target clients and record feedback. Gather qualitative data regarding their constraints.',
     'Complete 5 customer interviews and summarize the feedback.', 300, 'active', 3),
  (4, 'Launch Landing Page MVP',
     'Create a simple landing page showcasing the offer value proposition and signup form. Collect early subscriber signups.',
     'Publish your landing page and share the link.', 400, 'active', 4),
  (5, 'Submit Step 4 Milestone',
     'Consolidate all learnings, customer interviews, and MVP landing page analytics into the final execution summary.',
     'Submit your consolidated milestone summary.', 500, 'active', 5)
ON CONFLICT (task_order) DO NOTHING;


-- ============================================================================
-- 12. USER CONNECTIONS  (Follow graph for the Community page)
-- ============================================================================
CREATE TABLE IF NOT EXISTS user_connections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  follower_id TEXT NOT NULL,
  followed_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (follower_id, followed_name)
);

CREATE INDEX IF NOT EXISTS user_connections_follower_id_idx ON user_connections (follower_id);

ALTER TABLE user_connections ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon read" ON user_connections;
CREATE POLICY "Allow anon read" ON user_connections FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow anon insert" ON user_connections;
CREATE POLICY "Allow anon insert" ON user_connections FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow anon delete" ON user_connections;
CREATE POLICY "Allow anon delete" ON user_connections FOR DELETE USING (true);


-- ============================================================================
-- 13. CONTENT BUDDY AI  (Conversations, Messages, Saved Content, Usage Counters)
-- ============================================================================
CREATE TABLE IF NOT EXISTS ai_conversations (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT 'New Conversation',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_messages (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  conversation_id UUID NOT NULL REFERENCES ai_conversations(id) ON DELETE CASCADE,
  sender TEXT NOT NULL CHECK (sender IN ('user', 'assistant')),
  message TEXT NOT NULL,
  input_type TEXT NOT NULL CHECK (input_type IN ('text', 'voice', 'image')),
  image_url TEXT,
  content_type TEXT,
  language TEXT,
  tone TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS saved_ai_content (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id TEXT NOT NULL,
  conversation_id UUID REFERENCES ai_conversations(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'other'
    CHECK (category IN ('social_media', 'advertisement', 'business', 'personal', 'video_script', 'email', 'other')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_usage_counters (
  user_id TEXT NOT NULL,
  window_type TEXT NOT NULL CHECK (window_type IN ('day', 'minute')),
  window_start TIMESTAMP WITH TIME ZONE NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, window_type, window_start)
);

CREATE INDEX IF NOT EXISTS idx_ai_conversations_user ON ai_conversations(user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_messages_conversation ON ai_messages(conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_saved_ai_content_user ON saved_ai_content(user_id, created_at DESC);

ALTER TABLE ai_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE saved_ai_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_usage_counters ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all access for backend service role" ON ai_conversations;
DROP POLICY IF EXISTS "Allow all access for backend service role" ON ai_messages;
DROP POLICY IF EXISTS "Allow all access for backend service role" ON saved_ai_content;
DROP POLICY IF EXISTS "Allow all access for backend service role" ON ai_usage_counters;
CREATE POLICY "Allow all access for backend service role" ON ai_conversations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for backend service role" ON ai_messages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for backend service role" ON saved_ai_content FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for backend service role" ON ai_usage_counters FOR ALL USING (true) WITH CHECK (true);


-- ============================================================================
-- 14. (reserved — kept as a numbering placeholder to match the section
--      ordering in the migration guide; no additional tables here)
-- ============================================================================


-- ============================================================================
-- 15. STORAGE BUCKETS
-- ----------------------------------------------------------------------------
-- Every image/audio/PDF/video upload in this codebase funnels through exactly
-- 3 public buckets:
--   - "community"           generic uploads from the admin panel's single
--                            POST /api/upload route (server.js). Despite the
--                            name it holds carousel media, podcast covers +
--                            audio, e-book covers + PDFs, banners, and actual
--                            community-post media (folders like
--                            "podcast/covers", "ebooks/pdfs", etc.)
--   - "ai-content"          Content Buddy AI chat image attachments
--                            (imageUploadService.js), path pattern:
--                            {user_id}/{conversation_id}/{message_id}.jpg
--   - "support-attachments" ticket/feedback attachments uploaded directly
--                            from the Flutter app (support_service.dart)
-- ============================================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('community', 'community', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('ai-content', 'ai-content', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('support-attachments', 'support-attachments', true)
ON CONFLICT (id) DO NOTHING;

-- Public read for all 3 buckets (public URLs are used throughout the app).
DROP POLICY IF EXISTS "Public read - community" ON storage.objects;
CREATE POLICY "Public read - community" ON storage.objects
  FOR SELECT USING (bucket_id = 'community');

DROP POLICY IF EXISTS "Public read - ai-content" ON storage.objects;
CREATE POLICY "Public read - ai-content" ON storage.objects
  FOR SELECT USING (bucket_id = 'ai-content');

DROP POLICY IF EXISTS "Public read - support-attachments" ON storage.objects;
CREATE POLICY "Public read - support-attachments" ON storage.objects
  FOR SELECT USING (bucket_id = 'support-attachments');

-- Writes to "community" and "ai-content" only ever happen server-side from
-- admin-app, which uses the SUPABASE service-role key (bypasses RLS/storage
-- policies entirely) — so no INSERT/UPDATE/DELETE policy is required for
-- those two buckets to keep working exactly as today.
--
-- "support-attachments" is the one exception: the Flutter app uploads to it
-- directly using the anon key (see lib/support_service.dart), so it needs an
-- explicit public insert policy.
DROP POLICY IF EXISTS "Public insert - support-attachments" ON storage.objects;
CREATE POLICY "Public insert - support-attachments" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'support-attachments');

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
